### ISSUE TITLE
cv2.waitKey(1) function not implemented

### ISSUE THREAD

**Issue by riple** [jjhelmus/berryconda#36] opened 2018-07-30 01:09 UTC
I ran Microsoft-ELL tutorial on Pi 0 W, and it seems the opencv package is not compiled properly.
My version of opencv is
    opencv:      3.3.0-py36hcfffc66_0
It is installed by this command
    conda install -c microsoft-ell/label/pi_zero opencv
And the packages installed are
    Package plan for installation in environment /home/pi/berryconda3/envs/py36:
    The following NEW packages will be INSTALLED:

    bzip2:       1.0.6-1               lisaong
    ffmpeg:      3.2.4-hf767ee3_0
    giflib:      5.1.4-h3b1de47_0
    hdf5:        1.8.17-0
    jasper:      1.900.1-4             microsoft-ell
    jpeg:        9b-0                  microsoft-ell
    libgfortran: 3.0.0-1
    libpng:      1.6.29-0              microsoft-ell
    libtiff:     4.0.6-0
    libwebp:     0.5.2-hcb3eeb6_7
    numpy:       1.14.0-py36hebd9de5_0
    openblas:    0.2.19-0
    opencv:      3.3.0-py36hcfffc66_0
    x264:        20131217-hc5d671e_0

Here are the errors.

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvWaitKey, file /home/jhelmus/conda/conda-bld/opencv_1512232341522/work/modules/highgui/src/window.cpp, line 676
Traceback (most recent call last):
  File "tutorial.py", line 89, in <module>
    main()
  File "tutorial.py", line 49, in main
    while (cv2.waitKey(1) & 0xFF) == 0xFF:
cv2.error: /home/jhelmus/conda/conda-bld/opencv_1512232341522/work/modules/highgui/src/window.cpp:676: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvWaitKey

**Comment by jjhelmus** [comment] 2018-07-30 01:19
Closing of duplicate of #21.  The OpenCV in the `rpi` channel is not build with GUI support, pull requests adding this support would be welcome.

**Closed by jjhelmus** 2018-07-30 01:19 UTC
